server:
  port: 8888
  servlet:
    context-path: /database/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://%s:%s/%s?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mybatis/*.xml
#  type-aliases-package: com.github.dragonhht.database.manager.model
#  configuration:
#    map-underscore-to-camel-case: true